DELETE FROM dm01.BODENBEDECKUNG_BOFLAECHE;
DELETE FROM dm01.BODENBEDECKUNG_BBNACHFUEHRUNG;
 
INSERT INTO 
	dm01.BODENBEDECKUNG_BBNACHFUEHRUNG 
	(
		T_ID
		, NBIDENT 
		, IDENTIFIKATOR
		, BESCHREIBUNG 
		, PERIMETER 
		, GUELTIGKEIT 
		, GUELTIGEREINTRAG 
		, DATUM1 
	)
SELECT 
	T_ID 
	, NBIDENT 
	, IDENTIFIKATOR 
	, SUBSTRING(BESCHREIBUNG, 1, 29)
	, PERIMETER 
	, 'gueltig'
	, GUELTIGEREINTRAG 
	, GUELTIGEREINTRAG 
FROM 
	dmav.BODENBEDECKUNG_BBNACHFUEHRUNG 
;

/* Gueltigkeit wird aus der BB-Tabelle verwendet.
 * Falls es sich um ein projektiertes Gebäude handelt,
 * ist auch das NF-Objekt projektiert (egal, ob auch
 * ein reales Objekt dranhängt).
 */
UPDATE 
	dm01.BODENBEDECKUNG_BBNACHFUEHRUNG 
SET 
	GUELTIGKEIT = 'projektiert'
WHERE 
	T_ID IN 
	(
		SELECT DISTINCT
			ENTSTEHUNG 
		FROM 
			dmav.BODENBEDECKUNG_BODENBEDECKUNG AS bb
		WHERE 
			bb.OBJEKTSTATUS = 'projektiert'
	)
;

INSERT INTO 
	dm01.BODENBEDECKUNG_BOFLAECHE 
	(
		T_ID 
		, GEOMETRIE 
		, QUALITAET 
		, ART 
		, ENTSTEHUNG 
	)
SELECT 
	T_ID 
	, GEOMETRIE 
	, QUALITAETSSTANDARD 
	, BODENBEDECKUNGSART 
	, ENTSTEHUNG 
FROM 
	DMAV.BODENBEDECKUNG_BODENBEDECKUNG 
;



DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2SYMBOL;
DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2;
DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2NACHFUEHRUNG;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2NACHFUEHRUNG 
	(
		T_ID,
		NBIDENT, 
		IDENTIFIKATOR, 
		BESCHREIBUNG,
		GUELTIGEREINTRAG,
		DATUM1 
	)
SELECT 
	1,
	NBIDENT,
	'XXXX',
	'XXXX',
	CURRENT_DATE() AS foo,
	CURRENT_DATE() AS bar
FROM 
	dmav.FIXPUNKTEVKTGRIE2_LFP2 
LIMIT 1		
;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2 
	(
		T_ID
 		, NBIDENT 
 		, NUMMER 
 		, GEOMETRIE 
 		, HOEHEGEOM
 		, LAGEGEN 
 		, LAGEZUV 
 		, HOEHEGEN 
 		, HOEHEZUV 
 		, BEGEHBARKEIT 
 		, PUNKTZEICHEN 
 		, ENTSTEHUNG 
	)
	SELECT 
		T_ID 
		, NBIDENT 
		, NUMMER
		, GEOMETRIE 
		, HOEHENGEOMETRIE
		, (LAGEGENAUIGKEIT*100) 
		, CASE WHEN ISTLAGEZUVERLAESSIG IS TRUE THEN 'ja' ELSE 'nein' END
		, (HOEHENGENAUIGKEIT*100)
		, CASE WHEN ISTHOEHENZUVERLAESSIG IS TRUE THEN 'ja' ELSE 'nein' END
		, CASE WHEN BEGEHBAR IS TRUE THEN 'begehbar' ELSE 'nicht_begehbar' END
		, PUNKTZEICHEN
		, 1
	FROM 
		dmav.FIXPUNKTEVKTGRIE2_LFP2 
;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2SYMBOL 
	(
		ORI 
		, LFP2SYMBOL_VON 
	)

SELECT 
	SYMBOLORI 
	, T_ID 
FROM 
	dmav.FIXPUNKTEVKTGRIE2_LFP2 
;
