DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2SYMBOL;
DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2;
DELETE FROM dm01.FIXPUNKTEKATGRIE2_LFP2NACHFUEHRUNG;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2NACHFUEHRUNG 
	(
		T_ID,
		NBIDENT, 
		IDENTIFIKATOR, 
		BESCHREIBUNG,
		GUELTIGEREINTRAG,
		DATUM1 
	)
SELECT 
	1,
	NBIDENT,
	'XXXX',
	'XXXX',
	CURRENT_DATE() AS foo,
	CURRENT_DATE() AS bar
FROM 
	dmav.FIXPUNKTEVKTGRIE2_LFP2 
LIMIT 1		
;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2 
	(
		T_ID
 		, NBIDENT 
 		, NUMMER 
 		, GEOMETRIE 
 		, HOEHEGEOM
 		, LAGEGEN 
 		, LAGEZUV 
 		, HOEHEGEN 
 		, HOEHEZUV 
 		, BEGEHBARKEIT 
 		, PUNKTZEICHEN 
 		, ENTSTEHUNG 
	)
	SELECT 
		T_ID 
		, NBIDENT 
		, NUMMER
		, GEOMETRIE 
		, HOEHENGEOMETRIE
		, (LAGEGENAUIGKEIT*100) 
		, CASE WHEN ISTLAGEZUVERLAESSIG IS TRUE THEN 'ja' ELSE 'nein' END
		, (HOEHENGENAUIGKEIT*100)
		, CASE WHEN ISTHOEHENZUVERLAESSIG IS TRUE THEN 'ja' ELSE 'nein' END
		, CASE WHEN BEGEHBAR IS TRUE THEN 'begehbar' ELSE 'nicht_begehbar' END
		, PUNKTZEICHEN
		, 1
	FROM 
		dmav.FIXPUNKTEVKTGRIE2_LFP2 
;

INSERT INTO 
	dm01.FIXPUNKTEKATGRIE2_LFP2SYMBOL 
	(
		ORI 
		, LFP2SYMBOL_VON 
	)

SELECT 
	SYMBOLORI 
	, T_ID 
FROM 
	dmav.FIXPUNKTEVKTGRIE2_LFP2 
;
